AWSTemplateFormatVersion: 2010-09-09
Description: Template to create CodePipeline to build and deploy a Spring boot application as a docker container on ECS

Parameters:

  ProjectName:
    Type: String
    Description: The name of the project.
    Default: employee-service

  RepoName:
    Type: String
    Default: 'https://github.com/Polimetla-Develop/cicd-fargate-rds-api-gateway-1'

Resources:

  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: "{{resolve:ssm:/github/AuthToken:1}}" # Should be changed

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-ci
      Source:
        Type: GITHUB
        Location: !Ref RepoName
        BuildSpec: !Sub |
          version: 0.2
          phases:
            build:
              commands:
                - echo CODEBUILD_WEBHOOK_TRIGGER is $CODEBUILD_WEBHOOK_TRIGGER
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    DependsOn: CodeBuildSourceCredential
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildTrustPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}-ci
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}-ci:*