version: '2.1'

services:

  postgres:
    container_name: postgres_container
    image: $ECR_PUBLIC_REGISTRY/postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./postgres_data:/tmp/data
      - postgres:/data/postgres
    ports:
      - 5432:5432

  flyway:
    container_name: flyway_container
    image: $ECR_PUBLIC_REGISTRY/flyway/flyway:7
    env_file:
      - .env
    restart: on-failure:3
    command: info migrate
    volumes:
      - ./database:/tmp/database
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres: